name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/askara-backend/my-backend .

    - name: Push Docker image to GCR
      run: docker push gcr.io/askara-backend/my-backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy askara-backend \
        --image gcr.io/askara-backend/my-backend \
        --platform managed \
        --region europe-central2 \
        --allow-unauthenticated
